# Use the latest Ubuntu image
FROM ubuntu:latest

# Update APT and upgrade all Installed software
RUN apt-get update 
RUN apt-get upgrade -y

# Set the default command to print "Hello, World!"
CMD echo "Hello, World!"
