version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    networks:
      - app-network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"  # Expose only port 80 for the proxy
    depends_on:
      - front-end
      - back-end
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

